### ISSUE TITLE
x.stream.CloseSend undefined (type client.Stream has no field or method CloseSend)

### ISSUE THREAD

**Issue by dinglei19** [go-micro/generator#1]
Describe the bug:
I use Go Micro Cli init a service and make proto, a error occurred in *.pb.micro.go, x.stream.CloseSend undefined (type client.Stream has no field or method CloseSend).

I took a look and found that there is no CloseSend function in go-micro.dev/v4/client Stream.

This problem also exists in go-micro.dev/v4/server Stream.

**Comment by xpunch** [comment]
Please upgrade your go-micro.dev/v4 to latest version.
